//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoBusinessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILMES
    {
        public decimal ID { get; set; }
        public string TITULO { get; set; }
        public string DIRETOR { get; set; }
        public decimal ANO { get; set; }
        public string URL_IMDB { get; set; }
    }
}
