//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoBusinessLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILMES> FILMES { get; set; }
    
        public virtual int DELETE_FILME(Nullable<decimal> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_FILME", iDParameter);
        }
    
        public virtual int INSERT_FILME(Nullable<decimal> iD, string tITULO, Nullable<decimal> aNO, string iMDB_URL)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var tITULOParameter = tITULO != null ?
                new ObjectParameter("TITULO", tITULO) :
                new ObjectParameter("TITULO", typeof(string));
    
            var aNOParameter = aNO.HasValue ?
                new ObjectParameter("ANO", aNO) :
                new ObjectParameter("ANO", typeof(decimal));
    
            var iMDB_URLParameter = iMDB_URL != null ?
                new ObjectParameter("IMDB_URL", iMDB_URL) :
                new ObjectParameter("IMDB_URL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_FILME", iDParameter, tITULOParameter, aNOParameter, iMDB_URLParameter);
        }
    
        public virtual int UPDATE_FILME(Nullable<decimal> iD, string tITULO, Nullable<decimal> aNO, string iMDB_URL)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var tITULOParameter = tITULO != null ?
                new ObjectParameter("TITULO", tITULO) :
                new ObjectParameter("TITULO", typeof(string));
    
            var aNOParameter = aNO.HasValue ?
                new ObjectParameter("ANO", aNO) :
                new ObjectParameter("ANO", typeof(decimal));
    
            var iMDB_URLParameter = iMDB_URL != null ?
                new ObjectParameter("IMDB_URL", iMDB_URL) :
                new ObjectParameter("IMDB_URL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_FILME", iDParameter, tITULOParameter, aNOParameter, iMDB_URLParameter);
        }
    }
}
